export const SET_PROVIDER = "SET_PROVIDER";
export const LOAD_GETH_INFO = "LOAD_GETH_INFO";
export const LOAD_ADMIN_INFO = "LOAD_ADMIN_INFO";
export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";